Throw error if path not defined. Fix list output

diff --git a/config/get-seclists b/config/get-seclists
--- a/config/get-seclists
+++ b/config/get-seclists
@@ -1,12 +1,18 @@
 #!/bin/bash
 
+if [ -z "$1" ]; then
+    echo "Error: missing path argument. Please provide file path. List can be found in: https://github.com/danielmiessler/SecLists";
+    exit 1;
+fi
+
 FILE_PATH=$1
 
 OUTPUT=$(curl https://raw.githubusercontent.com/danielmiessler/SecLists/master/$FILE_PATH)
 
-echo $OUTPUT
+if [ -z "$2" ]; then
+    echo "$OUTPUT";
+    exit 0;
+fi
 
-if [ -z "$2" ]; then exit 0; fi
-
-echo $OUTPUT >> $2
+echo "$OUTPUT" >> $2
 
